TYPE=VIEW
query=select `sd`.`id` AS `device_id`,`sd`.`name` AS `device_name`,`sd`.`ip_address` AS `ip_address`,`psd`.`port_number` AS `port_number`,`psd`.`port_name` AS `port_name`,`psd`.`port_alias` AS `port_alias`,`psd`.`port_description` AS `port_description`,`psd`.`admin_status` AS `admin_status`,`psd`.`oper_status` AS `oper_status`,`psd`.`vlan_id` AS `vlan_id`,`psd`.`vlan_name` AS `vlan_name`,`psd`.`mac_address` AS `mac_address`,`psd`.`mac_addresses` AS `mac_addresses`,`psd`.`poll_timestamp` AS `poll_timestamp`,`mat`.`device_name` AS `mac_device_name`,`mat`.`ip_address` AS `mac_ip_address`,(select count(0) from `switchdb`.`alarms` `a` where `a`.`device_id` = `sd`.`id` and `a`.`port_number` = `psd`.`port_number` and `a`.`status` = \'active\') AS `active_alarm_count`,(select count(0) from `switchdb`.`port_change_history` `pch` where `pch`.`device_id` = `sd`.`id` and `pch`.`port_number` = `psd`.`port_number` and `pch`.`change_timestamp` > current_timestamp() - interval 24 hour) AS `changes_last_24h` from ((`switchdb`.`snmp_devices` `sd` join `switchdb`.`port_status_data` `psd` on(`sd`.`id` = `psd`.`device_id`)) left join `switchdb`.`mac_address_tracking` `mat` on(`psd`.`mac_address` = `mat`.`mac_address`)) where `psd`.`poll_timestamp` = (select max(`switchdb`.`port_status_data`.`poll_timestamp`) from `switchdb`.`port_status_data` where `switchdb`.`port_status_data`.`device_id` = `sd`.`id` and `switchdb`.`port_status_data`.`port_number` = `psd`.`port_number`)
md5=654f7905e604ea26c140ef5081d92401
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=0001771146985046659
create-version=2
source=SELECT \n    sd.id AS device_id,\n    sd.name AS device_name,\n    sd.ip_address,\n    psd.port_number,\n    psd.port_name,\n    psd.port_alias,\n    psd.port_description,\n    psd.admin_status,\n    psd.oper_status,\n    psd.vlan_id,\n    psd.vlan_name,\n    psd.mac_address,\n    psd.mac_addresses,\n    psd.poll_timestamp,\n    mat.device_name AS mac_device_name,\n    mat.ip_address AS mac_ip_address,\n    (SELECT COUNT(*) FROM alarms a \n     WHERE a.device_id = sd.id \n     AND a.port_number = psd.port_number \n     AND a.status = \'active\') AS active_alarm_count,\n    (SELECT COUNT(*) FROM port_change_history pch\n     WHERE pch.device_id = sd.id\n     AND pch.port_number = psd.port_number\n     AND pch.change_timestamp > DATE_SUB(NOW(), INTERVAL 24 HOUR)) AS changes_last_24h\nFROM snmp_devices sd\nINNER JOIN port_status_data psd ON sd.id = psd.device_id\nLEFT JOIN mac_address_tracking mat ON psd.mac_address = mat.mac_address\nWHERE psd.poll_timestamp = (\n    SELECT MAX(poll_timestamp) \n    FROM port_status_data \n    WHERE device_id = sd.id AND port_number = psd.port_number\n)
client_cs_name=latin1
connection_cl_name=latin1_swedish_ci
view_body_utf8=select `sd`.`id` AS `device_id`,`sd`.`name` AS `device_name`,`sd`.`ip_address` AS `ip_address`,`psd`.`port_number` AS `port_number`,`psd`.`port_name` AS `port_name`,`psd`.`port_alias` AS `port_alias`,`psd`.`port_description` AS `port_description`,`psd`.`admin_status` AS `admin_status`,`psd`.`oper_status` AS `oper_status`,`psd`.`vlan_id` AS `vlan_id`,`psd`.`vlan_name` AS `vlan_name`,`psd`.`mac_address` AS `mac_address`,`psd`.`mac_addresses` AS `mac_addresses`,`psd`.`poll_timestamp` AS `poll_timestamp`,`mat`.`device_name` AS `mac_device_name`,`mat`.`ip_address` AS `mac_ip_address`,(select count(0) from `switchdb`.`alarms` `a` where `a`.`device_id` = `sd`.`id` and `a`.`port_number` = `psd`.`port_number` and `a`.`status` = \'active\') AS `active_alarm_count`,(select count(0) from `switchdb`.`port_change_history` `pch` where `pch`.`device_id` = `sd`.`id` and `pch`.`port_number` = `psd`.`port_number` and `pch`.`change_timestamp` > current_timestamp() - interval 24 hour) AS `changes_last_24h` from ((`switchdb`.`snmp_devices` `sd` join `switchdb`.`port_status_data` `psd` on(`sd`.`id` = `psd`.`device_id`)) left join `switchdb`.`mac_address_tracking` `mat` on(`psd`.`mac_address` = `mat`.`mac_address`)) where `psd`.`poll_timestamp` = (select max(`switchdb`.`port_status_data`.`poll_timestamp`) from `switchdb`.`port_status_data` where `switchdb`.`port_status_data`.`device_id` = `sd`.`id` and `switchdb`.`port_status_data`.`port_number` = `psd`.`port_number`)
mariadb-version=100432
